server:
  port: 8070
spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: local
  config:
    import: "optional:classpath:application-secret.yml"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  datasource:
    url: jdbc:h2:./db_dev;DB_CLOSE_DELAY=-1; # DB 일관성 유지
    username: admin
    password:
    driver-class-name: org.h2.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true # 트랜잭션 충돌 방지
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
spring doc:
  default-produces-media-type: application/json
logging:
  level:
    com.ll.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: www.surl.oa.gg
    frontUrl: "https://${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "QUOTEME DEV"
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
  accessToken:
    expirationSec: 600
    jwt:
      secretKey: "sdfsd2312fdfs231k7845fddsfds234adcxzcc"
      accessTokenExpiration: 3600